databases:
  - name: sapna-billing-app
    databaseName: sapna-billing-app
    user: Umair
    plan: free

services:
  - type: web
    name: sapna-billing-app
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "ssh -i 'sapnaxerox2main.pem' -L 5432:localhost:5432 admin@ec2-15-206-149-166.ap-south-1.compute.amazonaws.com -N && bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        value: "postgresql://username:password@localhost:5432/database_name"
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2